#pragma once



#include <QPixmap>

#include <QString>

#include <cstdint>

#include <map>

#include <vector>



#define VIDEO_ASPECT_NUM 16

#define VIDEO_ASPECT_DEN 9



#define TITLE_BAR_HEIGHT 72
#define TITLE_BAR_LOGO_SIZE 36
#define TITLE_BAR_FONT_SIZE 20
#define TITLE_BAR_BUTTON_SIZE TITLE_BAR_HEIGHT
#define TITLE_BAR_ICON_SIZE 28
#define TITLE_BAR_H_MARGIN 10



#define LOGIN_DIALOG_WIDTH 1000

#define LOGIN_DIALOG_HEIGHT 620

#define LOGIN_DIALOG_RIGHT_WIDTH 520

#define LOGIN_DIALOG_RIGHT_HEIGHT 620



#define SMALL_VIDEO_WIDGET_WIDTH 480

#define SMALL_VIDEO_WIDGET_HEIGHT ((SMALL_VIDEO_WIDGET_WIDTH * VIDEO_ASPECT_DEN) / VIDEO_ASPECT_NUM)

#define MAX_REMOTE_VIDEO_WIDGETS 3



#define BIG_VIDEO_DEFAULT_WIDTH 1470

#define BIG_VIDEO_DEFAULT_HEIGHT ((BIG_VIDEO_DEFAULT_WIDTH * VIDEO_ASPECT_DEN) / VIDEO_ASPECT_NUM)



#define MAIN_WINDOW_DEFAULT_WIDTH (SMALL_VIDEO_WIDGET_WIDTH + BIG_VIDEO_DEFAULT_WIDTH)

#define MAIN_WINDOW_DEFAULT_HEIGHT (TITLE_BAR_HEIGHT + BIG_VIDEO_DEFAULT_HEIGHT + Bottonbar_HEIGHT)



#define Bottonbar_HEIGHT 144

#define BOTTONBAR_H_MARGIN 18

#define BOTTONBAR_ITEM_SPACING 0

#define BOTTONBAR_TOOL_BTN_WIDTH 126

#define BOTTONBAR_TOOL_BTN_MIN_WIDTH 78

#define BOTTONBAR_TOOL_BTN_HEIGHT Bottonbar_HEIGHT

#define BOTTONBAR_TOOL_ICON_SIZE 48

#define BOTTONBAR_TOOL_FONT_SIZE 10

#define BOTTONBAR_ICON_TEXT_SPACING 2

#define BOTTONBAR_END_BTN_GAP 24

#define BOTTONBAR_END_BTN_WIDTH 190

#define BOTTONBAR_END_BTN_HEIGHT 72

#define BOTTONBAR_END_FONT_SIZE 15



#define LOCAL_USER_UID 123456



#define AGORA_APP_ID "5c3ae3f88921453f8d97f60c955af82f"



#define SHARE_WINDOW_ITEM_WIDTH 480
#define SHARE_WINDOW_ITEM_HEIGHT ((SHARE_WINDOW_ITEM_WIDTH * VIDEO_ASPECT_DEN) / VIDEO_ASPECT_NUM)
#define SHARE_WINDOW_ITEM_CAPTION_HEIGHT 52

#define SHARE_SCREEN_DIALOG_WIDTH 1280
#define SHARE_SCREEN_DIALOG_TITLE_HEIGHT 52
#define SHARE_SCREEN_DIALOG_TITLE_FONT_SIZE 26
#define SHARE_SCREEN_DIALOG_SECTION_FONT_SIZE 22
#define SHARE_SCREEN_DIALOG_SECTION_LABEL_HEIGHT 36
#define SHARE_SCREEN_DIALOG_NAME_FONT_SIZE 16
#define SHARE_SCREEN_DIALOG_NAV_FONT_SIZE 22
#define SHARE_SCREEN_DIALOG_START_BTN_HEIGHT 48
#define SHARE_SCREEN_DIALOG_START_BTN_MIN_WIDTH 140
#define SHARE_SCREEN_DIALOG_START_BTN_FONT_SIZE 16
#define SHARE_SCREEN_DIALOG_CLOSE_SIZE 52
#define SHARE_SCREEN_DIALOG_CLOSE_ICON_SIZE 24
#define SHARE_SCREEN_DIALOG_FOOTER_HEIGHT 64
#define SHARE_SCREEN_DIALOG_PADDING 16
#define SHARE_SCREEN_CAROUSEL_ROW_HEIGHT 44
#define SHARE_SCREEN_COLUMN_HEIGHT (SHARE_SCREEN_DIALOG_SECTION_LABEL_HEIGHT + SHARE_WINDOW_ITEM_HEIGHT + SHARE_WINDOW_ITEM_CAPTION_HEIGHT + SHARE_SCREEN_CAROUSEL_ROW_HEIGHT + 20)
#define SHARE_SCREEN_DIALOG_HEIGHT (SHARE_SCREEN_DIALOG_TITLE_HEIGHT + SHARE_SCREEN_DIALOG_PADDING * 2 + SHARE_SCREEN_COLUMN_HEIGHT + SHARE_SCREEN_DIALOG_FOOTER_HEIGHT)



#define RECORDING_VIDEO_WIDTH 1920

#define RECORDING_VIDEO_HEIGHT 1080

#define RECORDING_REMOTE_VIDEO_WIDTH SMALL_VIDEO_WIDGET_WIDTH

#define RECORDING_REMOTE_VIDEO_HEIGHT SMALL_VIDEO_WIDGET_HEIGHT

#define RECORDING_VIDEO_FPS 15

#define RECORDING_AUDIO_SAMPLE_RATE 48000

#define RECORDING_AUDIO_CHANNELS 1



#define SMALL_VIDEO_LIST_ITEM_SPACING 12

struct window_share_info

{

	enum WindowType { Screen, Window };



	int64_t sourceId = 0;

	QString name;

	WindowType windowType = Window;

	QPixmap pixmap;

};



using VecWindowShareInfo = std::vector<window_share_info>;

